openapi: 3.0.0
info:
  title: Wordlift API
  version: 1.0.0
paths:
  /wordlift/v1/main-ingredients:
    get:
      operationId: get
      summary: Get main ingredients
      description: Retrieves a list of main ingredients based on the provided query string.
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A JSON array of main ingredients.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Invalid request.
        "401":
          description: Authentication failed.
