openapi: 3.0.0
info:
  title: Wordlift Term Matches API
  version: 1.0.0
servers:
  - url: https://example.com
components:
  schemas:
    TermMatch:
      type: object
      properties:
        name:
          type: string
          description: The name of the term
          required: true
        id:
          type: integer
          format: int64
          description: The ID of the term.
          required: true
        match_name:
          type: string
          description: The name of the matched term.
        match_id:
          type: integer
          format: int64
          description: The ID of the matched term.
        match_jsonld:
          type: object
          description: The JSON-LD of the matched term.
      required:
        - name
        - id
        - match_name
        - match_id

    Page:
      type: object
      properties:
        self:
          type: string
          description: The URL of the current page.
          required: true
        first:
          type: string
          description: The URL of the first page.

        prev:
          type: string
          description: The URL of the previous page.

        next:
          type: string
          description: The URL of the next page.

        last:
          type: string
          description: The URL of the last page.

        items:
          type: array
          items:
            $ref: "#/components/schemas/TermMatch"
          required: true

paths:
  /wordlift/v1/term-matches:
    get:
      operationId: list
      description: Returns a list of term matches for a given taxonomy.
      parameters:
        - name: taxonomy
          in: query
          description: Name of the taxonomy to retrieve term matches for.
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          description: Cursor for pagination.
          schema:
            type: string
        - name: limit
          in: query
          description: Limit
          schema:
            type: number
        - name: filter
          in: query
          description: Filter
          schema:
            type: string
            enum:
              - MATCHED
              - UNMATCHED
              - ALL
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Page"

  /wordlift/v1/term-matches/{term_id}/matches:
    post:
      operationId: create
      description: Creates a term match for the given term ID.
      parameters:
        - name: term_id
          in: path
          description: The ID of the term to create a match for.
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The JSON-LD of the term match.
        required: true
        content:
          application/ld+json:
            example:
              name: "lorem"
              id: 123
              match_name: "ipsum"
              match_id: 456
              match_jsonld: {}
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TermMatch"

  /wordlift/v1/term-matches/{term_id}/matches/{match_id}:
    put:
      operationId: update
      description: Updates a term match for the given term and match IDs.
      parameters:
        - name: term_id
          in: path
          description: The ID of the term to update a match for.
          required: true
          schema:
            type: integer
            format: int64
        - name: match_id
          in: path
          description: The ID of the match to update.
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: The JSON-LD of the term match.
        required: true
        content:
          application/ld+json:
            example:
              name: "lorem"
              id: 123
              match_name: "ipsum"
              match_id: 456
              match_jsonld: {}
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TermMatch"

        "404":
          description: Not Found
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
