services:
  Wordlift\Api\Api_Service:
    factory: [ 'Wordlift\Api\Default_Api_Service', 'get_instance' ]
    class: Wordlift\Api\Default_Api_Service

  Wordlift\Modules\Events\Post_Entity\Events_Post_Entity_Runner:
    class: Wordlift\Modules\Events\Post_Entity\Events_Post_Entity_Runner
    arguments: [ '@Wordlift\Api\Default_Api_Service' ]

  Wordlift\Modules\Events\Term_Entity\Events_Term_Entity_Runner:
    class: Wordlift\Modules\Events\Term_Entity\Events_Term_Entity_Runner
    arguments: [ '@Wordlift\Api\Default_Api_Service' ]

  Wordlift\Modules\Events\Options_Entity\Events_Term_Entity_Runner:
    class: Wordlift\Modules\Events\Term_Entity\Events_Term_Entity_Runner
    arguments: [ '@Wordlift\Api\Default_Api_Service' ]
